### PR TITLE
Refactor service #84

### PR DESCRIPTION
**Pull request by NimperX**

### CODE REVIEW

**Comment by NimperX** [comment]
@CrazyMarvin As a favor for Hacktoberfest contributors including me if you can add `hacktoberfest-accepted` label to every closed pr during the october month it would really helpful for them.

**Comment by CrazyMarvin** [comment]
> @CrazyMarvin As a favor for Hacktoberfest contributors including me if you can add `hacktoberfest-accepted` label to every closed pr during the october month it would really helpful for them.

The PRs to this repo should already count in your Hacktoberfest dashboard. Can you please check?

**Comment by NimperX** [comment]
> 
> 
> > @CrazyMarvin As a favor for Hacktoberfest contributors including me if you can add `hacktoberfest-accepted` label to every closed pr during the october month it would really helpful for them.
> 
> The PRs to this repo should already count in your Hacktoberfest dashboard. Can you please check?

@CrazyMarvin It has been marked as a PR in hacktoberfest dashboard. But according to digital ocean's update the public repos with hacktoberfest topic or PRs with hacktoberfest-accepted labels will be counted for the contribution. Read the updated document [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by CrazyMarvin** [comment]
> PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
) 

In my opinion we are fine since we have October, this is a public repo with the `hacktoberfest` topic and your PR is merged.
But I will add the `hacktoberfest-accepted` label to this PR for you.

**Pull request merged**
